<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="camera" params="parent *origin">

  <!-- Constants for robot dimensions -->
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="1.5" /> <!-- Link 1 -->
  <xacro:property name="height2" value="0.5" /> <!-- Link 2 -->
  <xacro:property name="height3" value="0.5" /> <!-- Link 3 -->
  <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

  <joint name="base_joint" type="fixed">
    <xacro:insert_block name="origin" />
    <parent link="${parent}"/>
    <child link="base_link" />
  </joint>

  <!-- Base Link -->
  <link name="base_link">
    <!-- <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision> -->

    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height1}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
        izz="${mass / 12.0 * (width*width + width*width)}"/>
      </inertial>
    </link>

    <joint name="joint1" type="continuous">
      <parent link="base_link"/>
      <child link="link1"/>
      <origin xyz="0 ${width} ${height1 - axel_offset}" rpy="0 1.5708 0"/>
      <axis xyz="1 0 0"/>
      <dynamics damping="0.7"/>
    </joint>

    <!-- Middle Link -->
    <link name="link1">
      <collision>
        <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
        <geometry>
          <box size="${width} ${width} ${height2}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
        <geometry>
          <box size="${width} ${width} ${height2}"/>
        </geometry>
        <material name="yellow"/>
      </visual>

      <inertial>
        <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia
          ixx="${mass / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0"
          iyy="${mass / 12.0 * (height2*height2 + width*width)}" iyz="0.0"
          izz="${mass / 12.0 * (width*width + width*width)}"/>
        </inertial>
      </link>

      <!-- <joint name="joint2" type="continuous">
        <parent link="link1"/>
        <child link="link2"/>
        <origin xyz="0 ${width} ${height2 - axel_offset*2}" rpy="0 0 0"/>
        <axis xyz="1 0 0"/>
        <dynamics damping="0.7"/>
      </joint> -->

      <!-- Top Link -->
      <!-- <link name="link2">
        <collision>
          <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
          <geometry>
            <box size="${width} ${width} ${height3}"/>
          </geometry>
        </collision>

        <visual>
          <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
          <geometry>
            <box size="${width} ${width} ${height3}"/>
          </geometry>
          <material name="orange"/>
        </visual>

        <inertial>
          <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
          <mass value="${mass}"/>
          <inertia
            ixx="${mass / 12.0 * (width*width + height3*height3)}" ixy="0.0" ixz="0.0"
            iyy="${mass / 12.0 * (height3*height3 + width*width)}" iyz="0.0"
            izz="${mass / 12.0 * (width*width + width*width)}"/>
          </inertial>
        </link> -->

        <joint name="tool_joint" type="fixed">
          <origin xyz="0 0 1" rpy="0 0 0" />
          <parent link="link1"/>
          <child link="tool_link" />
        </joint>

        <!-- Tool Link -->
        <link name="tool_link">
        </link>

        <joint name="hokuyo_joint" type="fixed">
          <axis xyz="0 1 0" />
          <origin xyz="0 0 ${height3 - axel_offset/2}" rpy="0 0 0"/>
          <parent link="link1"/>
          <child link="hokuyo_link"/>
        </joint>

        <!-- Hokuyo Laser -->
        <link name="hokuyo_link">
          <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
              <box size="0.1 0.1 0.1"/>
            </geometry>
          </collision>

          <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
              <mesh filename="file://$(find segmentation)/meshes/hokuyo.dae"/>
            </geometry>
          </visual>

          <inertial>
            <mass value="1e-5" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
          </inertial>
        </link>

        <joint name="camera_joint" type="fixed">
          <axis xyz="0 1 0" />
          <origin xyz="${camera_link} 0 ${height3 - axel_offset*2}" rpy="0 0 0"/>
          <parent link="link1"/>
          <child link="camera_link"/>
        </joint>

        <!-- Camera -->
        <link name="camera_link">
          <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
              <box size="${camera_link} ${camera_link} ${camera_link}"/>
            </geometry>
          </collision>

          <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
              <box size="${camera_link} ${camera_link} ${camera_link}"/>
            </geometry>
            <material name="red"/>
          </visual>

          <inertial>
            <mass value="1e-5" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
          </inertial>
        </link>

        <!-- generate an optical frame http://www.ros.org/reps/rep-0103.html#suffix-frames
        so that ros and opencv can operate on the camera frame correctly -->
        <joint name="camera_optical_joint" type="fixed">
          <!-- these values have to be these values otherwise the gazebo camera image
          won't be aligned properly with the frame it is supposedly originating from -->
          <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
          <parent link="camera_link"/>
          <child link="camera_link_optical"/>
        </joint>

        <link name="camera_link_optical">
        </link>
  </xacro:macro>

</robot>
